INSERT INTO USERS(ID, USER_NAME, BIRTH_DATE)
VALUES (10001, 'Piotr', current_date());

INSERT INTO USERS(ID, USER_NAME, BIRTH_DATE)
VALUES (10002, 'Jacek', current_date());

INSERT INTO USERS(ID, USER_NAME, BIRTH_DATE)
VALUES (10003, 'Marcin', current_date());

INSERT INTO POSTS(ID, DESCRIPTION, USER_ID)
VALUES (20001, 'I want to learn AWS', 10001);

INSERT INTO POSTS(ID, DESCRIPTION, USER_ID)
VALUES (20002, 'I want to learn DevOps', 10001);

INSERT INTO POSTS(ID, DESCRIPTION, USER_ID)
VALUES (20003, 'I want to learn SQL', 10002);